language: java

sudo: false

after_success:
  - bash < (curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - danila.shabanov.1995@gmail.com
    on_success: never
    on_failure: always